### ISSUE TITLE
Upgrade CAEN libs

### ISSUE THREAD

**Issue by gennadiy-fnal** [SBNSoftware/sbndaq-artdaq#59]
Upgrade CAEN libs

**Comment by wbadgett** [comment]
Pippo says ICARUS tried out this branch and have signed off on it

**Comment by wbadgett** [comment]
Oops, I meant Matteo, not Pippo

**Comment by aaduszki** [comment]
For completeness, I believe we had at least 3 updates since this issue was open. Unfortunately I cannot really comment about details of what was happening in May 2022.

#66 May 23, 2023
caencomm              v1_2a
caenvme               v2_50
caendigitizer         v2_12_0

#103 Feb 28, 2023, used in ICARUS since May 21, 2023
caencomm              v1_6_0
caenvme               v3_4_0
caendigitizer         v2_17_3

#107 tested last week at FD, to be used as default soon:
caencomm              v1_6_0a
caenvme               v3_4_4
caendigitizer         v2_17_3a

**Comment by gennadiy-fnal** [comment]
This is a duplicate of issue #107.
